version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgres://db_user:db_password@database:5432/db_name
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - php
    ports:
      - "8080:80"

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
