<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdw1xGl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdw1xGl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZdw1xGl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZdw1xGl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZdw1xGl\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zdw1xGl',
    'container.build_id' => '45c3152f',
    'container.build_time' => 1683424275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdw1xGl');
